ALTER TABLE DOCTOR
ADD CONSTRAINT PK_DOCTOR_USER_NAME
PRIMARY KEY (DOCTOR_USER_NAME);

ALTER TABLE DOCTOR
ADD CONSTRAINT FK_DOCTOR_USER_NAME
FOREIGN KEY (DOCTOR_USER_NAME) REFERENCES "USER"(User_Name);

ALTER TABLE PATIENT
ADD CONSTRAINT PK_PATIENT_USER_NAME
PRIMARY KEY (PATIENT_USER_NAME);

ALTER TABLE PATIENT
ADD CONSTRAINT FK_PATIENT_USER_NAME
FOREIGN KEY (PATIENT_USER_NAME) REFERENCES "USER"(User_Name);

ALTER TABLE APPOINTMENT
ADD CONSTRAINT FK_APPOINTMENT_USER
FOREIGN KEY (Patient_UserName) REFERENCES PATIENT(PATIENT_USER_NAME);

ALTER TABLE APPOINTMENT
ADD CONSTRAINT FK_Clinic_ID
FOREIGN KEY (Clinic_ID) REFERENCES CLINIC(ID);

ALTER TABLE POSTS
ADD CONSTRAINT FK_Posts_Clinic_ID
FOREIGN KEY (Post_Clinic_ID) REFERENCES CLINIC(ID);

ALTER TABLE DOCTOR
ADD CONSTRAINT FK_DOCTOR_CLINIC_ID
FOREIGN KEY (Clinic_ID) REFERENCES CLINIC(ID);

ALTER TABLE CONAS
ADD CONSTRAINT FK_Appointment_ID
FOREIGN KEY (Appointment_ID) REFERENCES APPOINTMENT(ID);

ALTER TABLE CONAS
ADD CONSTRAINT FK_Services_ID
FOREIGN KEY (Services_ID) REFERENCES SERVICES(ID);